CREATE TABLE IF NOT EXISTS `ai_playerbot_run_summary` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `run_started_at` DATETIME NOT NULL,
  `run_ended_at` DATETIME NOT NULL,
  `source_events` VARCHAR(255) NOT NULL DEFAULT '',
  `source_perf` VARCHAR(255) NOT NULL DEFAULT '',
  `bot_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `event_rows` INT UNSIGNED NOT NULL DEFAULT 0,
  `tick_avg_ms` FLOAT NOT NULL DEFAULT 0,
  `tick_max_ms` FLOAT NOT NULL DEFAULT 0,
  `map_avg_ms` FLOAT NOT NULL DEFAULT 0,
  `map_max_ms` FLOAT NOT NULL DEFAULT 0,
  `playerbots_avg_ms` FLOAT NOT NULL DEFAULT 0,
  `playerbots_max_ms` FLOAT NOT NULL DEFAULT 0,
  `corpses_delta` INT NOT NULL DEFAULT 0,
  `notes` TEXT,
  PRIMARY KEY (`id`),
  KEY `idx_run_window` (`run_started_at`, `run_ended_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ai_playerbot_learned_blackspot` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source_run_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `blackspot_type` VARCHAR(32) NOT NULL DEFAULT 'path',
  `map_id` INT NOT NULL DEFAULT -1,
  `bucket_x` INT NOT NULL DEFAULT 0,
  `bucket_y` INT NOT NULL DEFAULT 0,
  `radius` FLOAT NOT NULL DEFAULT 25,
  `reason` VARCHAR(128) NOT NULL DEFAULT '',
  `hit_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `penalty` FLOAT NOT NULL DEFAULT 1,
  `confidence` FLOAT NOT NULL DEFAULT 0,
  `first_seen_at` DATETIME NOT NULL,
  `last_seen_at` DATETIME NOT NULL,
  `enabled` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_blackspot_unique` (`blackspot_type`, `map_id`, `bucket_x`, `bucket_y`, `reason`),
  KEY `idx_blackspot_lookup` (`enabled`, `map_id`, `bucket_x`, `bucket_y`),
  KEY `idx_blackspot_reason` (`blackspot_type`, `reason`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ai_playerbot_objective_stats` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source_run_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `objective_type` VARCHAR(32) NOT NULL DEFAULT '',
  `quest_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `entry` INT UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `map_id` INT NOT NULL DEFAULT -1,
  `bucket_x` INT NOT NULL DEFAULT 0,
  `bucket_y` INT NOT NULL DEFAULT 0,
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `success_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `failure_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `avg_seconds` FLOAT NOT NULL DEFAULT 0,
  `pain_score` FLOAT NOT NULL DEFAULT 0,
  `learned_penalty` FLOAT NOT NULL DEFAULT 0,
  `last_failure_reason` VARCHAR(128) NOT NULL DEFAULT '',
  `first_seen_at` DATETIME NOT NULL,
  `last_seen_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_objective_lookup` (`objective_type`, `quest_id`, `entry`),
  KEY `idx_objective_area` (`map_id`, `bucket_x`, `bucket_y`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ai_playerbot_behavior_model` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `model_key` VARCHAR(64) NOT NULL,
  `model_version` INT UNSIGNED NOT NULL DEFAULT 1,
  `model_type` VARCHAR(32) NOT NULL DEFAULT 'rules',
  `status` VARCHAR(16) NOT NULL DEFAULT 'candidate',
  `trained_from_run_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `notes` TEXT,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_model_version` (`model_key`, `model_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ai_playerbot_task_sample` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sampled_at` DATETIME NOT NULL,
  `bot_guid` INT UNSIGNED NOT NULL DEFAULT 0,
  `account_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `race` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `class` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `spec_tab` TINYINT NOT NULL DEFAULT -1,
  `level` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `map_id` INT NOT NULL DEFAULT -1,
  `instance_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `zone_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `area_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `bucket_x` INT NOT NULL DEFAULT 0,
  `bucket_y` INT NOT NULL DEFAULT 0,
  `task_type` VARCHAR(32) NOT NULL DEFAULT '',
  `is_random_bot` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `has_real_master` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `group_size` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `is_group_leader` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `is_dungeon` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `is_raid` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `is_battleground` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `is_combat` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `is_alive` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `health_pct` FLOAT NOT NULL DEFAULT 0,
  `power_pct` FLOAT NOT NULL DEFAULT 0,
  `elapsed_ms` INT UNSIGNED NOT NULL DEFAULT 0,
  `level_delta` INT NOT NULL DEFAULT 0,
  `xp_delta` INT NOT NULL DEFAULT 0,
  `money_delta` INT NOT NULL DEFAULT 0,
  `active_quests` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `complete_quests` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `rewarded_quests` INT UNSIGNED NOT NULL DEFAULT 0,
  `active_quest_delta` INT NOT NULL DEFAULT 0,
  `complete_quest_delta` INT NOT NULL DEFAULT 0,
  `target_entry` INT UNSIGNED NOT NULL DEFAULT 0,
  `target_level` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `target_health_pct` FLOAT NOT NULL DEFAULT 0,
  `notes` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_task_sample_bot_time` (`bot_guid`, `sampled_at`),
  KEY `idx_task_sample_context` (`task_type`, `class`, `spec_tab`, `level`, `map_id`, `zone_id`),
  KEY `idx_task_sample_lod` (`map_id`, `bucket_x`, `bucket_y`, `task_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ai_playerbot_combat_sample` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ended_at` DATETIME NOT NULL,
  `bot_guid` INT UNSIGNED NOT NULL DEFAULT 0,
  `race` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `class` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `spec_tab` TINYINT NOT NULL DEFAULT -1,
  `level` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `map_id` INT NOT NULL DEFAULT -1,
  `instance_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `zone_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `area_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `bucket_x` INT NOT NULL DEFAULT 0,
  `bucket_y` INT NOT NULL DEFAULT 0,
  `combat_context` VARCHAR(32) NOT NULL DEFAULT '',
  `group_size` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `is_dungeon` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `is_raid` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `is_battleground` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `duration_ms` INT UNSIGNED NOT NULL DEFAULT 0,
  `target_entry` INT UNSIGNED NOT NULL DEFAULT 0,
  `target_level` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `target_is_player` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `target_switches` INT UNSIGNED NOT NULL DEFAULT 0,
  `min_health_pct` FLOAT NOT NULL DEFAULT 100,
  `min_power_pct` FLOAT NOT NULL DEFAULT 100,
  `ended_alive` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `death_observed` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `level_delta` INT NOT NULL DEFAULT 0,
  `xp_delta` INT NOT NULL DEFAULT 0,
  `money_delta` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_combat_sample_context` (`combat_context`, `class`, `spec_tab`, `level`, `map_id`, `zone_id`),
  KEY `idx_combat_sample_target` (`target_entry`, `class`, `spec_tab`, `level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ai_playerbot_lod_projection_stat` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `model_key` VARCHAR(64) NOT NULL DEFAULT 'baseline',
  `task_type` VARCHAR(32) NOT NULL DEFAULT '',
  `class` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `spec_tab` TINYINT NOT NULL DEFAULT -1,
  `level_min` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `level_max` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `map_id` INT NOT NULL DEFAULT -1,
  `zone_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `group_size_min` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `group_size_max` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `sample_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `xp_per_hour` FLOAT NOT NULL DEFAULT 0,
  `money_per_hour` FLOAT NOT NULL DEFAULT 0,
  `quest_complete_per_hour` FLOAT NOT NULL DEFAULT 0,
  `death_per_hour` FLOAT NOT NULL DEFAULT 0,
  `confidence` FLOAT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_lod_projection_lookup` (`model_key`, `task_type`, `class`, `spec_tab`, `level_min`, `level_max`, `map_id`, `zone_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
